spring:
  application:
    name: junmo-website
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jummo-website-dev-db;MODE=MYSQL
    username: jun
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true